# DATABASE CONFIG
spring.datasource.url=jdbc:postgresql://localhost:15001/assignment
spring.datasource.username=postgres
spring.datasource.password=secret99

# JPA CONFIG
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=Z5DA2qW3tB07ptxQ1kbVgyKnfnDoh4LCr0VevpLZLr0=
